### PR TITLE
Initial support for kotlin

### PR DESCRIPTION
**Pull request by knobo**

### CODE REVIEW

**Comment by knobo** [comment]
I don't know it this is good enough to merge. I will anyway work some more on this.

**Comment by ubolonton** [comment]
Can you add a Kotlin file with example code? I think `examples/hl.kt` might be a good name.
We don't have automated highlighting tests at the moment, but such a file would still be useful for "look-n-feel tours".
(We can add examples for other languages later on.)

**Comment by knobo** [comment]
Example file, like this: [examples/hl.kt](https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/84/files#diff-5405e036b96044ebf399cb422156ebaf3f0892e080a72a46f72f56ccfb316d9a)

**Comment by knobo** [comment]
Should I do something more with this?

**Comment by meain** [comment]
I was trying it out locally and looks like there is some issues with the highlight queries. I am not entirely sure as to what is going on. *This theme only highlights function names and strings.*

|Built-in|Tree-sitter|
|---|---|
| EMACS-Screenshot-2022-09-24-19:49:42 |EMACS-Screenshot-2022-09-24-19:49:03|

**Comment by jcs090218** [comment]
Kotlin is added in #212. Feel free to open PRs for improvements!

**Pull request closed without merging**
