### PR TITLE
Update repository url for CI

### PR DESCRIPTION
**Pull request by jcs090218**

### CODE REVIEW

**Comment by ubolonton** [comment]
CI is currently broken
- The newly-created org in Azure Pipelines cannot run pipelines yet.
- I'm trying to move to GitHub Actions, but for some reason the workflows got disabled after a while.

We'll need to wait for support's responses before updating the info.

**Comment by jcs090218** [comment]
I'm keen to work on this package! Let me know if I can help! 😁 👍

**Comment by jcs090218** [comment]
> You can take ownership of languages you are interested in and have time for.

Awesome! I can also do some elisp tasks like review basic PRs (from Elisp). But I am not very good at Rust, so I would have pass on that for now. Hopefully, I can pick up the skill very soon! 😅 

> P.S. I'm trying out your GitHub action setup-emacs-windows. It seems to work well.

What do you need from CI? I never used `azure-pipelines` so I may need sometime to read workflows your were trying to achieve.

Of course, only if you need help! 😁

**Comment by ubolonton** [comment]
> > You can take ownership of languages you are interested in and have time for.
> 
> Awesome! I can also do some elisp tasks like review basic PRs (from Elisp). But I am not very good at Rust, so I would have pass on that for now. Hopefully, I can pick up the skill very soon! 😅
> 

I mean ownership of specific language grammars and queries. For example: keeping the grammar up-to-date by reviewing upstream changes and updating the submodule, improving hl queries and making sure they are consistent.

But yeah, ELisp and Rust contributions are welcome too!

> What do you need from CI? I never used `azure-pipelines` so I may need sometime to read workflows your were trying to achieve.
> 

I just need Emacs with dynamic module enabled. Your `setup-emacs-windows` helps with that for GitHub Actions. For Azure Pipelines, I had some custom code that makes it sort of work. I plan to switch to GitHub Actions going forward, so don't worry too much about making things work on Azure Pipelines.

**Pull request merged**
