### PR TITLE
Bump PHP & update highlights

### PR DESCRIPTION
**Pull request by elken**
Update the PHP repo, and update the highlights to reflect changes

### CODE REVIEW

**Comment by ubolonton** [comment]
Thanks! And sorry for the late reply. I was too busy at work.

We have auto-release set up for merges, so it would be nice to have an entry in CHANGELOG.md. Can you add that?

**Comment by elken** [comment]
Not a problem! I'll add one shortly :)

**Comment by elken** [comment]
@ubolonton a new entry or under "unreleased"?

**Comment by ubolonton** [comment]
It should be a new bullet point under `# Unreleased`.

**Comment by elken** [comment]
Added, probably want to squash merge this; or I can rebase into 1 commit if you'd prefer

**Pull request merged**
