### PR TITLE
Lua support

### PR DESCRIPTION
**Pull request by ymarco**
I did mess a lot with the queries until I reached feature-parity with the Python queries, by eye at least.
image

### CODE REVIEW

**Comment by jumper047** [comment]
Looks awesome! Any news on merging this PR?

**Comment by ymarco** [comment]
I'm done, ready for review from my point

**Comment by meain** [comment]
@ymarco Could you rebase your changes on top of master and we should be good to go :D

**Comment by ymarco** [comment]
> @ymarco Could you rebase your changes on top of master and we should be good to go :D

Sure, done

**Pull request merged**
