### PR TITLE
fix(r): highlights.scm file name

### PR DESCRIPTION
**Pull request by ShuguangSun**
Signed-off-by: Shuguang Sun <shuguang79@qq.com>

### CODE REVIEW

**Comment by maikol-solis** [comment]
Oh, sorry for the typo in the file name!

The highlights are from https://github.com/r-lib/tree-sitter-r/blob/main/queries/highlights.scm (where I think @ShuguangSun copied originally).

**Comment by ShuguangSun** [comment]
It is not about the file content, but the file name. It should be "highlights.scm" instead off "highlight.scm"

**Comment by meain** [comment]
@maikol-solis @ShuguangSun I understand it is a file name change. What I meant was that the highlight queries in "highlights.scm" gets picked up now but are now causing tree-sitter to highlight r buffers incorrectly. This is caused by as the capture names used in highlights.scm is not what the tree-sitter implementation here expects. The screenshot on the left in the above comment was with normal highlighting and the right with is with tree-sitter highlighting.

**Comment by maikol-solis** [comment]
Yes, sorry for the confusion. This PR fixes correctly the filename. I pushed it with the wrong filename in the first PR.

**Comment by ShuguangSun** [comment]
> @maikol-solis @ShuguangSun I understand it is a file name change. What I meant was that the highlight queries in "highlights.scm" gets picked up now but are now causing tree-sitter to highlight r buffers incorrectly. This is caused by as the capture names used in highlights.scm is not what the tree-sitter implementation here expects. The screenshot on the left in the above comment was with normal highlighting and the right with is with tree-sitter highlighting.

Now I see what you mean. The current highlights.scm is the one shipped by tree-sitter-r which might be to aggressive for highlight. It is why I wrote `tree-sitter-ess-r`. Might we need to modify the highlights.scm to some kind of emacs style.

**Comment by ShuguangSun** [comment]
Now fixed. It is due the scm file make all as variable.

**Review by meain — APPROVED** [review]
@ShuguangSun Thank you, this look great now.

**Pull request merged**
