### PR TITLE
Add matlab grammar

### PR DESCRIPTION
**Pull request by acristoffers**

### CODE REVIEW

**Comment by acristoffers** [comment]
Ok, a lot of force-pushes later, I have what is considered the final version of the parser itself. I would like to know if there are changes that need to be made to the query file, as I'm currently using it and it works just fine, but I'm not familiar with the way your project handles those. I believed I have followed the instructions correctly, but I could not find a complete list of available query captures, so I don't if I missed something. 

This parser was just accepted in Neovim (nvim-treesitter/nvim-treesitter#4944), and I mention that to show that, even though it is new, it went through a revision and got some changes and bug fixes already, and I consider it to be in a stable/release version. It will see bugfixes in the future, but not major changes.

**Comment by acristoffers** [comment]
I got the queries from the elisp file, so now it should be 100% compliant.

**Comment by meain** [comment]
Changes look good to me. Just wondering if we should do something about `matlab-file-font-lock-keywords` 🤔

**Comment by acristoffers** [comment]
I set it to an empty list and it worked for me, but I must admit that I have no idea what that should actually be.

**Comment by acristoffers** [comment]
In the last 2 force-pushes I bump the repo version because I fixed some bugs in the parser and also change the priority of the operators captures in highlight so single-quoted strings get highlighted correctly.

**Comment by meain** [comment]
> I set it to an empty list and it worked for me, but I must admit that I have no idea what that should actually be.

This is more of a `matlab-mode` problem, let me merge this in. Thanks for the PR and the grammar :D.

**Pull request merged**
