### PR TITLE
Add haskell-mode and highlights.scm

### PR DESCRIPTION
**Pull request by lastgosumatt**
Just little edit to improve Haskell support.

### CODE REVIEW

**Comment by meain** [comment]
Hey, @lastgosumatt , the code looks good but there was an issue in the azure CI which was causing issues for us which is now fixed. Would it be possible for you to rebase with master and push?

**Comment by lastgosumatt** [comment]
Should be good now. :)

**Comment by meain** [comment]
Missed mentioning this earlier, could you also add a changelog entry.

**Comment by lastgosumatt** [comment]
Like this?

**Review by meain — APPROVED** [review]
LGTM

**Comment by meain** [comment]
Just waiting for the CI to be done and we should be good to go :D

**Pull request merged**
