### PR TITLE
Update Elixir grammar to official Elixir-lang repo

### PR DESCRIPTION
**Pull request by ZachFontenot**
The current elixir submodule has been archived as the Elixir team has their own tree-sitter grammar. This PR just points at the new repo. I'm not so confident with submodules, so if there is anything else that needs to be done let me know. 

Also, I believe the Elisp just pulls in the `queries/highlights.scm` so this should just work?

### CODE REVIEW

**Comment by wingyplus** [comment]
@ubolonton ping. :)

**Comment by ubolonton** [comment]
Sorry for the late reply. I was too busy with life.

> Also, I believe the Elisp just pulls in the `queries/highlights.scm` so this should just work?

These queries were copied. The intention was to modify them to better fit Emacs's conventions. If the upstream queries have changed, please feel free to update the queries as well. We have CI tests for queries' validity.

**Comment by wingyplus** [comment]
> Sorry for the late reply. I was too busy with life.
> 
> > Also, I believe the Elisp just pulls in the `queries/highlights.scm` so this should just work?
> 
> These queries were copied. The intention was to modify them to better fit Emacs's conventions. If the upstream queries have changed, please feel free to update the queries as well. We have CI tests for queries' validity.

I’ve a patch for query on this repo. Not sure if we can merge this patch first. I’ll open a new PR for the query. :)

**Comment by wingyplus** [comment]
> Sorry for the late reply. I was too busy with life.
> 
> > Also, I believe the Elisp just pulls in the `queries/highlights.scm` so this should just work?
> 
> These queries were copied. The intention was to modify them to better fit Emacs's conventions. If the upstream queries have changed, please feel free to update the queries as well. We have CI tests for queries' validity.

Thanks! I’ll open a PR for query soon. :)

**Pull request merged**
