### PR TITLE
Add Markdown support

### PR DESCRIPTION
**Pull request by egrajeda**
This implementation is the one listed in the official tree-sitter website.

### CODE REVIEW

**Comment by meain** [comment]
Hey, the CI had a few issues which I have now fixed in master. Could you rebase your branch on top of latest master?

**Comment by egrajeda** [comment]
Yep no problem, just did it. Let's see if it works now.

**Comment by meain** [comment]
The CI ran into two other issues (https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/154 and https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/159) once the previous one was fixed, could you rebase it once more on top of current master.

**Comment by egrajeda** [comment]
Done, it should be good now.

**Pull request merged**
