### PR TITLE
ci: Fix release

### PR DESCRIPTION
**Pull request by jcs090218**
See full log: https://github.com/jcs-PR/tree-sitter-langs/actions/runs/5329926270.

### CODE REVIEW

**Comment by meain** [comment]
Hmm, looks like we are seeing some trouble with the Windows builds. Don't think these are specific to this change, but let me take a look.

**Comment by jcs090218** [comment]
> Hmm, looks like we are seeing some trouble with the Windows builds.

Can you point me where? It's all green. 🤔 Thanks! ;)

**Comment by meain** [comment]
Looks like the rerun was successful.
Here is the link to a failing run: https://github.com/emacs-tree-sitter/tree-sitter-langs/actions/runs/5330120596/attempts/2?pr=190

**Comment by meain** [comment]
We are back to being able to release again. Thanks a lot @jcs090218

**Pull request merged**
