### PR TITLE
queries(julia): add basic highlights.scm

### PR DESCRIPTION
**Pull request by jeetelongname**
This is a work in progress for the moment but should be complete soonish

[](https://github.com/hlissner/doom-emacs/pull/5401)

### CODE REVIEW

**Comment by tecosaur** [comment]
Why not add https://github.com/tree-sitter/tree-sitter-julia ?

**Comment by jeetelongname** [comment]
the Julia grammer is already in the [repo](https://github.com/emacs-tree-sitter/tree-sitter-langs/tree/master/repos), what I was meant to do was include a query file that allows for syntax highlighting (text object support is already implemented in nvim and just needs to be ported afik), I just need to get around to finishing it :sweat_smile:

**Comment by tecosaur** [comment]
Poke. Also, the julia tree sitter submodule could do with an update.

**Comment by jeetelongname** [comment]
Thought I had responded to this. turns out no

> Its hard to work on a set of queries in a language you don't work in :sweat_smile: 
> that being said ill fiddle with it more
> as for the grammer, I can bump that but you will have to bare with me as I sort out my internet (which does not allow me to use git over ssh)

**Comment by jeetelongname** [comment]
I have found its hard to write queries for a language you do not use
:sweat_smile:, I will send in a PR to bump the grammer though

Regards,
– *Jeetaditya Chatterjee* 
/Sent using my text editor/

**Pull request closed without merging**
