### PR TITLE
ci: Build with Eask

### PR DESCRIPTION
**Pull request by jcs090218**
For #178.

@meain I know you would like to avoid CI changes if possible (https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/154#issuecomment-1368714544), so feel free to close this PR.

**Intention:** It seems like @ubolonton is busy and not able to respond. 🤔 So I've opened this PR so we don't block the development due to the build tool (Cask).

See log: https://github.com/jcs-PR/tree-sitter-langs/actions/runs/5296926346 (it's all green ✅)

### CODE REVIEW

**Comment by meain** [comment]
Thanks for the PR. I think it is about time we moved to eask.

> @meain I know you would like to avoid CI changes if possible (https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/154#issuecomment-1368714544), so feel free to close this PR.

My idea was "if it ain't broke, don't fix it", but I guess it is broken now and trying to fix cask setup on windows has proven to be a lost cause to me.

**Comment by meain** [comment]
@jcs090218 Seems like macOS installation is running into some trouble on master
https://github.com/emacs-tree-sitter/tree-sitter-langs/actions/runs/5318622745/jobs/9630271755

**Comment by jcs090218** [comment]
Yeah, this is the upstream issue from https://github.com/cachix/install-nix-action (recently is unstable).

You will get the same error with `purcell/setup-emacs` too. The current workaround is to re-run the failed jobs, and it will eventually succeed.

**Comment by meain** [comment]
Ahh, I see. Let me try rerunning it.

---

I did not dig much deeper into it, but there seems to be a fix in a newer version.
Ref: https://github.com/cachix/install-nix-action/issues/183

**Comment by meain** [comment]
Looks like that took care of things. :D

**Comment by meain** [comment]
@jcs090218 The release CI seems to be acting up. There are issues outside `eask` and `setup-emacs` but they do sometimes fail too. 🤔 
https://github.com/emacs-tree-sitter/tree-sitter-langs/actions/runs/5321892790/jobs/9638377303

**Comment by jcs090218** [comment]
I've made the fix in #190, please review the PR. :)

**Pull request merged**
